trigger:
  - master

jobs:
  - job: publish_new_data
    displayName: "Publish new timing data to S3"
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          set -e
          pip install setuptools
          pip install --user awscli
          echo "##vso[task.prependpath]$HOME/.local/bin"
        displayName: "Install awscli"
      - template: ci/azure-install-rust.yml
      - script: git clone https://github.com/rust-lang/rust --depth 200
        displayName: "Clone Rust"
      - script: |
          mkdir cache
          RUST_LOG=publish=debug cargo run --bin publish-data-to-s3 ./rust ./cache
        displayName: "Collect data"
      - script: aws s3 cp --recursive ./cache s3://rust-ci-timing-tracker/
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        displayName: "Upload data to s3"
      - script: |
          RUST_LOG=build=debug cargo run --bin build-site ./rust ./cache ./html
        displayName: "Build gh-pages"
      - script: |
          set -e
          source ci/setup-git.sh
          cd html
          git init
          git add .
          git commit -m "Deploy $BUILD_SOURCEVERSION"
          git push git@github.com:alexcrichton/rust-ci-timing-tracker master:gh-pages -f
        displayName: "Push to gh-pages"
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          GITHUB_DEPLOY_KEY: '$(GITHUB_DEPLOY_KEY)'
