[package]
name = "tracker"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ['derive'] }
log = "0.4"
env_logger = "0.6"
flate2 = "1.0"
